Style/Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

AllCops:
  Exclude:
    - 'run'
