#!/usr/bin/env ruby
require './autoload'
primes = Primes::Generator.new.generate(ARGV.fetch(0, 10).to_i)
calculator = Calculators::Multiplication.new(primes)
# Formatters::CLI.new(primes, calculator.matrix).display
